fix(datatable): Add searchable for each columns on datatable
SpoonX/aurelia-datatable pull request #104
Opened 2018-01-22 08:42 UTC by nvtin

This is about adding one option which is called `searchable` for each column on datatable. I have updated document as well.

2018-01-22 08:46 UTC, nvtin commented
Hi @RWOverdijk I completely forgot to update the pull request about adding searchable for each column. But I can't update the old commit message to match message format. So I closed that PR and make this new pull request. Can you review and merge it? Thank you so much.

2018-01-22 15:44 UTC, RWOverdijk requested changes

2018-01-22 15:44 UTC, RWOverdijk commented on src/datatable.js
> +          searchable: typeof column.searchable === 'boolean' ? column.searchable : true
Align consecutive colons

2018-01-22 15:44 UTC, RWOverdijk commented
I think it's a feat and not a fix

2018-01-22 15:44 UTC, RWOverdijk commented
@jeremyvergnas quick review?

2018-01-22 15:48 UTC, jeremyvergnas approved these changes
Looks good to me 👍

2018-01-22 16:05 UTC, nvtin commented
@RWOverdijk Thanks for your feedback on this PR. I have just updated the code follow your review. Can you review it again?

2018-01-24 15:02 UTC, RWOverdijk approved these changes

2018-01-24 15:03 UTC, merged

2018-01-24 15:13 UTC, RWOverdijk commented
If you run `gulp test` you'll see there are linting errors. I fixed those and published v0.9.0