fix(datatable): datatable rows displayed and not empty on IE11
SpoonX/aurelia-datatable pull request #107
Opened 2018-02-20 15:34 UTC by edmunfollen

This fix makes the data-table rows to be displayed and not empty on IE11

2018-02-20 16:09 UTC, VMBindraban requested changes

2018-02-20 16:09 UTC, VMBindraban commented on src/bootstrap/datatable.html
> +      <tr if.bind="!loading" containerless repeat.for="row of data">
http://aurelia.io/docs/api/templating/function/containerless/

Now it will render without the `tr`.
Please remove the `containerless`.

2018-02-20 16:10 UTC, VMBindraban commented
Adding `?w=1` to the query will make the review much easier.

2018-02-20 16:17 UTC, VMBindraban approved these changes

2018-02-21 12:23 UTC, merged

2018-02-21 12:24 UTC, RWOverdijk commented
Published as 0.9.2