feat(project): Add gather data
SpoonX/aurelia-datatable pull request #61
Opened 2016-10-04 15:37 UTC by jeremyvergnas

feat(project): Add gather data

Useful when we need to export all the data of the datatable for instance.

2016-10-04 17:21 UTC, doktordirk requested changes

2016-10-04 17:21 UTC, doktordirk commented on src/datatable.js
> +    return this.repository.find(criteria || {}, true).then(result => {
either criteria = {} or criteria || {}

2016-10-04 17:21 UTC, doktordirk commented on src/datatable.js
> +    }).catch(error => {
the then result part isn't doing anything

2016-10-04 17:21 UTC, doktordirk commented on src/datatable.js
> +    });
tricky. re.throw the error or not. i see you decided against @RWOverdijk thoughts. i guess when the event is used, re-throwing would just annoy

2016-10-04 17:21 UTC, doktordirk commented on src/bootstrap/datatable.html
> +          <a click.delegate="selected(row)" innerhtml.bind="displayValue(row, columnLabel.column) | convertManager: columnLabel.converter"></a>
what's the motivation? adding sanitizeHTML converter would have been one

2016-10-05 08:04 UTC, jeremyvergnas commented on src/bootstrap/datatable.html
> +          <a click.delegate="selected(row)" innerhtml.bind="displayValue(row, columnLabel.column) | convertManager: columnLabel.converter"></a>
We want to be able to use HTML tags in our column. In our case we need it to show barcodes.

2016-10-05 08:04 UTC, jeremyvergnas commented on src/datatable.js
> +    return this.repository.find(criteria || {}, true).then(result => {
Indeed

2016-10-05 08:21 UTC, jeremyvergnas commented on src/datatable.js
> +    });
It is using the same pattern we use all over the datatable plugin.

2016-10-05 10:14 UTC, VMBindraban commented
Update docs with new feature.

2016-10-05 10:46 UTC, doktordirk commented on src/bootstrap/datatable.html
> +          <a click.delegate="selected(row)" innerhtml.bind="displayValue(row, columnLabel.column) | convertManager: columnLabel.converter"></a>
i see. a separate commit (message) would have been nice though. 

i wounder if not `| sanitize` could/should be added. thoughts?

2016-10-05 12:08 UTC, VMBindraban requested changes
Update docs with new feature.

2016-10-05 13:11 UTC, doktordirk approved these changes

2016-10-05 13:16 UTC, VMBindraban commented
Fixes https://github.com/SpoonX/aurelia-datatable/issues/59

2016-10-05 14:18 UTC, jeremyvergnas commented on src/bootstrap/datatable.html
> +          <a click.delegate="selected(row)" innerhtml.bind="displayValue(row, columnLabel.column) | convertManager: columnLabel.converter"></a>
You probably mean the value converter `sanitizeHTML`. For some reason, it would break the datatable...

2016-10-06 12:48 UTC, merged