Make it work with array as columns
SpoonX/aurelia-datatable pull request #69
Opened 2016-11-25 10:02 UTC by jeremyvergnas

- Make columns usable as array of objects
- Make populate usable as array of strings

2016-11-25 10:07 UTC, RWOverdijk requested changes

2016-11-25 10:07 UTC, RWOverdijk commented on doc/usage.md
> +  columns = [{
Can't I just do `'id'`?

2016-11-25 10:07 UTC, RWOverdijk commented on src/datatable.js
> +    else if(Array.isArray(this.populate)){
Else goes on same line as closing bracket

2016-11-25 10:07 UTC, RWOverdijk commented on src/datatable.js
> +      let labels = this.columns.map(column => {
Just return the map?

2016-11-25 10:10 UTC, jeremyvergnas commented on doc/usage.md
> +  columns = [{
Wanted to show that we can used nested object. Maybe `group.name` is a better example then

2016-11-25 10:10 UTC, RWOverdijk commented on doc/usage.md
> +  columns = [{
👍

2016-11-25 10:31 UTC, jeremyvergnas commented
@RWOverdijk Done

2016-11-25 10:35 UTC, RWOverdijk approved these changes

2016-11-25 10:36 UTC, RWOverdijk commented
@doktordirk Could you double check? :)

2016-11-25 12:11 UTC, doktordirk commented
@RWOverdijk looks fine

2016-11-29 09:50 UTC, bas080 approved these changes

2016-11-29 10:02 UTC, VMBindraban approved these changes

2016-11-29 14:31 UTC, VMBindraban commented
Tested and works fine!

2016-11-29 18:47 UTC, merged